### PR TITLE
Use media_ids in api upload

### PR DESCRIPTION
**Pull request by mmn**
I want to accept the media_ids parameter from Twitter clients, so I need to do it in prepare (and then use it in handle). Since handle was the only function touched in this call I figured I can just remove all the other ones for now and then we can aim to migrate ApiQvitterStatusesUpdateAction into ApiStatusesUpdateAction :)

### CODE REVIEW

**Comment by hannesmannerheim** [comment]
looks like you removed my "post_to_groups"-argument? i wonder if that will break qvitter group correction feature

**Comment by hannesmannerheim** [comment]
maybe better to just route ApiQvitterStatusesUpdate to its own url instead of overwriting GNU social's

**Comment by hannesmannerheim** [comment]
the group correcting seems broken anyway...

**Comment by hannesmannerheim** [comment]
no! it's not broken. i just failed to save a file :)

**Comment by mmn** [comment]
Wups, yes I accidentally removed that! Didn't see. That could've otherwise been solved with:

`parent::prepare();
post_to_group_stuff;
return true;`

But your solution of just having a different path worked just fine too of course!

**Pull request closed without merging**
