### PR TITLE
Check if qvitternotice is >191 and not 255

### PR DESCRIPTION
**Pull request by fxdwg**
The column value in table config is of varchar(191) and not 255 which is the check done for qvittersidenotices...

### CODE REVIEW

**Comment by fxdwg** [comment]
Would be preferrable to have a larger column - to get better sidebar notifications on qvitter :) - html code takes a lot of chars.

**Comment by fxdwg** [comment]
It was change 12th Feburary 2015 to varchar(191) - don't know why. Don't understand @mmn comment. "varchar(191)   not 255 because utf8mb4 takes more space"
https://git.gnu.io/gnu/gnu-social/commit/2f86cd860231f92213950d439e9a109b7a5f11c4

Would be nice to have the field to 1024 or something, because HTML takes a lot of char's

**Comment by hannesmannerheim** [comment]
i suspected it had to do with that. the db was converted to utf8mb4 to enable emoji-support. but why not just have a _text_ field? it's not like the column will be used as a key or index

**Comment by mmn** [comment]
Just making it a text would be great. Those 255 to 191 changes were mostly made automatically with 'grep' and 'sed' so I made no further analysis of _which_ text fields I was changing (except where I ran into trouble, such as with file URLs where I solved the indexing with a urlhash field).

**Pull request merged**
