### PR TITLE
second XSS in search

### PR DESCRIPTION
**Pull request by mmn**

### CODE REVIEW

**Comment by mmn** [comment]
Damnit, this didn't fix it either. Maybe you can have a look @hannesmannerheim ? I'll keep looking, but this javascript logic is not overseeable...

**Comment by mmn** [comment]
Ah, it's the data-stream-header attribute that needs escaping.

**Comment by hannesmannerheim** [comment]
i still don't see the real problem with someone xss:ing themselves? :)

**Comment by mmn** [comment]
It's a real issue and not only XSS:ing themselves.

Consider that it's a popular site. People want drone accounts there. They go to a random forum somewhere, like comments on Reddit or Imgur or whatever. And they post quitter.es search links (of course with a link bait like "this is me nude!"). When clicking that, if logged in to quitter.es, the logged in user's entire session is in jeopardy and may be transferred via javascript to remote parties. Including perhaps the password which is sent with each request.

**Comment by hannesmannerheim** [comment]
your absolutely right! i'm lacking in imagination :) although the url would look very suspicious, it could be hidden with a url shortener

**Comment by mmn** [comment]
I _think_ I managed to push the updated branch here now. Try this for quitter.se : 
(copypaste it if github fucks up the link...)
https://quitter.se/search/notice?q="><script>alert("XSS")<%2Fscript>

And then consider that you could download whichever code you want from anywhere and run it with eval() or something.

(guess why I'm running NoScript and Request Policy... ;))

**Comment by hannesmannerheim** [comment]
i'm checking this out. i think we need to do this before it even gets into the localstorage history

**Comment by mmn** [comment]
Awesome. I get confused by javascript. Remember me to dumpsterdive something nice for you when I get the chance.

**Comment by hannesmannerheim** [comment]
this should stop it https://github.com/hannesmannerheim/qvitter/commit/15daae0a3632b5bfd199fa2976e21835d8af8ef4

**Comment by mmn** [comment]
Much more elegant. Will my first pull request affect this in any way? (like double escaping)

Thanks again. Seems to work on my instances.

**Comment by mmn** [comment]
Oooooh. My fix will fix the stuff in the "history-container" for logged in users. That's why I experience this.

Will all future history-container-entries be fixed by this? In that case it's ok.

**Comment by mmn** [comment]
@hannesmannerheim I just confirmed that your fix won't take care of the history-container element. Even after clearing all caches and whatnot, including local data, and searching for a different XSS-term - the new term popped up in an alert box.

I'll be running with the applied patch on quitter.es and now go eat some food. Woo, food!

**Comment by hannesmannerheim** [comment]
ok, weird, checking it out...

**Comment by hannesmannerheim** [comment]
right, my fix only stops those who enter by url. 

https://github.com/hannesmannerheim/qvitter/commit/679e02ab0b6949329524a6d2847eb15ae0a3d018 also stops it if someone is fooled into entering script into the search box

**Comment by hannesmannerheim** [comment]
i'm closing this if it's considered fixed now. i think it should be :)

**Pull request closed without merging**
